# Generated by Django 2.2.1 on 2019-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190618_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name_chat',
            field=models.CharField(default='Private', max_length=80),
        ),
    ]
