# Generated by Django 2.2.1 on 2019-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='select_user',
            field=models.BooleanField(default=False),
        ),
    ]
