# Generated by Django 2.2.1 on 2019-06-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_authuser_select_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='select_user',
        ),
    ]
