# Generated by Django 2.2.1 on 2019-06-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name_chat',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
