# Generated by Django 2.2.1 on 2019-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190618_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name_chat',
            field=models.CharField(max_length=80),
        ),
    ]
